### PR TITLE
perf(invokeazurerequest): :zap: removed string concatenation

### PR DESCRIPTION
**Pull request by prubis**
Much faster and far less memory usage through sending objects down the  pipeline rather than concatting strings. Discovered this perf issue when I was trying to use `Get-MDEMachine` in an environment with tens of thousands of enrolled machines.

### CODE REVIEW

**Comment by prubis** [comment]
Hi @itpropro , I think the failing check was happening even before my PR, could you please take a look?

**Comment by itpropro** [comment]
Hey,
Good find and nice performance improvement!
The failing test seems unrelated to your commit, I will fix it and merge your changes today.

**Comment by itpropro** [comment]
Have you updated the wiki submodule @prubis ?
If not, please execute 

```
Set-Location wiki
git pull
Set-Location ..
```

And commit. After that I can merge :)

**Comment by prubis** [comment]
Hmm, I didn't make any changes in the wiki so figured it wasn't necessary, but I might have missed something. I've init-ed and updated the wiki, but then there's nothing for me to commit as far as I can tell:
```powershell
C:\Repos\PSMDE> git submodule update --init --recursive
Submodule 'wiki' (https://github.com/Visorian/PSMDE.wiki.git) registered for path 'wiki'
Cloning into 'C:/Repos/PSMDE/wiki'...
Submodule path 'wiki': checked out '5a7c6b202a1f07c1e3bca0b0021a2310ec36f39e'
C:\Repos\PSMDE> git status
On branch prubis-perf-invokeazurerequest
Your branch is up to date with 'origin/prubis-perf-invokeazurerequest'.

nothing to commit, working tree clean
C:\Repos\PSMDE>
```

Unless I missed something?

**Pull request merged**
